### ISSUE TITLE
#Adding IPS feature along with IDS and OpenAppID as an another option.

### ISSUE THREAD

**Issue by rbshadow** [joanbono/Snorter#17]
I am working with this.

**Comment by joanbono** [comment]
I think it's easy to implement. To add this, user could do `-i $INTERFACE` , so if `$INTERFACE` is `eth0:eth1`, it will be in IPS mode, I think.

**Comment by rbshadow** [comment]
It works only in afpacket inline mode. But for NFQ some new packages need to install. So what do you think I should do?

**Comment by joanbono** [comment]
mmm, I got to think about it... Maybe it's better to wait until the Snort 3.0 release, which will work like a charm as IPS...

**Comment by rbshadow** [comment]
Ok then.

**Comment by rbshadow** [comment]
Let's wait for Snort 3.0.
