### ISSUE TITLE
Error upon docker usage

### ISSUE THREAD

**Issue by geekscrapy** [joanbono/Snorter#25]
Trying to build this in the docker container but I'm unsure how it's supposed to work. The following is the error I get when running from your example, but as far as I can see it would be quite a rewrite to make it usable in docker? The docker build flag doesn't take port or environment variables as far as I know. What version of docker are you running this under? TIA!

```
#docker build SnorterDock -p 80:80 -e OINKCODE=6207xxxx -e INTERFACE=eth0
unknown shorthand flag: 'p' in -p
See 'docker build --help'.
```

**Comment by joanbono** [comment]
Hi @geekscrapy , try the following:

```bash
#docker build SnorterDock -e OINKCODE=6207xxxx -e INTERFACE=eth0
```

After build complete, do:

```bash
#docker run YOUR_SNORTER_DOCKER -p 80:80 
```  

I think there's a typo in the README file.

**Comment by geekscrapy** [comment]
Thanks, just tried this and it doesn't work as it then asks for edits via the cmdline which cannot be completed via a docker build. This is another issue altogether though I guess

**Comment by joanbono** [comment]
Okai got the point. I’m closing this one as is related to #26
