### ISSUE TITLE
oinkcode as env variable for docker

### ISSUE THREAD

**Issue by Xumeiquer** [joanbono/Snorter#3]
I think it would be useful to change the dockerfile in the way that it can catch the oinkcode from the environment variable.

**Comment by joanbono** [comment]
Solved.

Now it's in the [README.md](https://github.com/joanbono/Snorter/blob/master/README.md) how to pass the `OINKCODE` and the `INTERFACE` to the `Dockerfile`.

Also, `Dockerfile` is updated 😃 

Thanks a lot for the issue, and the **StackOverflow** 😄 

*** 
## Updated `Dockerfile` content

~~~~
#Kali docker with SNORT + BARNYARD2 + PULLEDPORK
#Version 0.1.0
From kalilinux/kali-linux-docker:latest
MAINTAINER Joan Bono <@joan_bono> && Alvaro Diaz <@alvarodh5>

RUN apt-get update && apt-get upgrade -y && apt-get install -y git curl wget
RUN git clone https://github.com/joanbono/Snorter.git /opt/Snorter
RUN /opt/Snorter/src/Snorter.sh -o OINKCODE -i INTERFACE
USER root
WORKDIR /opt/Snorter
~~~~
